#!/usr/bin/env python3
"""Add a small runtime-tuning API to the pinned scroll-inertia module.

The upstream module stays pinned and unmodified in Git. This script patches the
local checkout idempotently before a PG1KB build so My Keeb Studio can tune a
few safe parameters at runtime.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

EXPECTED_SHA = "f7dadefee453d555fe066d13a3de3bb60739b45e"
PATCH_MARKER = "PG1KB_RUNTIME_API_PATCH_V1"


def fail(message: str) -> None:
    raise SystemExit(f"ERROR: {message}")


def replace_once(text: str, old: str, new: str, label: str) -> str:
    count = text.count(old)
    if count != 1:
        fail(f"{label}: expected exactly one match, found {count}")
    return text.replace(old, new, 1)


def main() -> None:
    if len(sys.argv) != 2:
        fail("usage: patch-scroll-inertia-runtime.py <scroll-inertia-repo>")

    root = Path(sys.argv[1]).expanduser().resolve()
    src_path = root / "src" / "input_processor_scroll_inertia.c"
    cmake_path = root / "CMakeLists.txt"
    header_path = root / "include" / "zmk" / "input_processors" / "scroll_inertia_runtime.h"

    if not src_path.is_file() or not cmake_path.is_file():
        fail(f"not a scroll-inertia checkout: {root}")

    try:
        head = subprocess.check_output(
            ["git", "-C", str(root), "rev-parse", "HEAD"], text=True
        ).strip()
    except (OSError, subprocess.CalledProcessError) as exc:
        fail(f"cannot read scroll-inertia git revision: {exc}")

    if head != EXPECTED_SHA:
        fail(
            "unexpected scroll-inertia revision: "
            f"{head} (expected {EXPECTED_SHA}); reset/checkout the pinned revision first"
        )

    header_path.parent.mkdir(parents=True, exist_ok=True)
    header_path.write_text(
        """/* PG1KB_RUNTIME_API_PATCH_V1
 * Runtime tuning API for zmk-input-processor-scroll-inertia.
 * Generated by tools/patch-scroll-inertia-runtime.py.
 */
#pragma once

#include <stdint.h>
#include <zephyr/device.h>

enum zmk_scroll_inertia_runtime_param {
    ZMK_SCROLL_INERTIA_RUNTIME_ENABLED = 0,
    ZMK_SCROLL_INERTIA_RUNTIME_START,
    ZMK_SCROLL_INERTIA_RUNTIME_MOVE,
    ZMK_SCROLL_INERTIA_RUNTIME_STOP,
};

int zmk_scroll_inertia_runtime_set(
    const struct device *dev, enum zmk_scroll_inertia_runtime_param param, int32_t value);
int zmk_scroll_inertia_runtime_get(
    const struct device *dev, enum zmk_scroll_inertia_runtime_param param, int32_t *value);
""",
        encoding="utf-8",
    )

    cmake = cmake_path.read_text(encoding="utf-8")
    if "zephyr_include_directories(include)" not in cmake:
        cmake = "zephyr_include_directories(include)\n\n" + cmake
        cmake_path.write_text(cmake, encoding="utf-8")

    src = src_path.read_text(encoding="utf-8")
    if PATCH_MARKER in src:
        print("scroll-inertia runtime API already patched")
        return

    src = replace_once(
        src,
        "#include <zephyr/input/input.h>\n",
        "#include <zephyr/input/input.h>\n#include <errno.h>\n",
        "errno include",
    )
    src = replace_once(
        src,
        '#include "scroll_inertia_math.h"\n',
        '#include "scroll_inertia_math.h"\n#include <zmk/input_processors/scroll_inertia_runtime.h>\n',
        "runtime header include",
    )

    src = replace_once(
        src,
        "    /* Delayed work items */\n",
        "    /* PG1KB_RUNTIME_API_PATCH_V1\n"
        "     * Runtime copy starts from the DT config and may be safely tuned without\n"
        "     * modifying the const devicetree-backed config object in flash. */\n"
        "    struct scroll_inertia_config runtime_cfg;\n"
        "    bool runtime_enabled;\n\n"
        "    /* Delayed work items */\n",
        "runtime state fields",
    )

    old = "    const struct scroll_inertia_config *cfg = data->dev->config;\n"
    count = src.count(old)
    if count != 2:
        fail(f"work-handler config pointers: expected 2 matches, found {count}")
    src = src.replace(
        old,
        "    const struct scroll_inertia_config *cfg = &data->runtime_cfg;\n\n"
        "    if (!data->runtime_enabled) {\n"
        "        return;\n"
        "    }\n",
    )

    src = replace_once(
        src,
        "    const struct scroll_inertia_config *cfg = dev->config;\n\n"
        "    int32_t ax = effective_axis(cfg);\n",
        "    const struct scroll_inertia_config *cfg = &data->runtime_cfg;\n\n"
        "    if (!data->runtime_enabled) {\n"
        "        return ZMK_INPUT_PROC_CONTINUE;\n"
        "    }\n\n"
        "    int32_t ax = effective_axis(cfg);\n",
        "input-handler config pointer",
    )

    runtime_api = r'''
/* ------------------------------------------------------------------ */
/* Runtime tuning API                                                  */
/* ------------------------------------------------------------------ */

int zmk_scroll_inertia_runtime_set(const struct device *dev,
                                   enum zmk_scroll_inertia_runtime_param param,
                                   int32_t value) {
    if (dev == NULL) {
        return -EINVAL;
    }

    struct scroll_inertia_data *data = dev->data;

    switch (param) {
    case ZMK_SCROLL_INERTIA_RUNTIME_ENABLED:
        data->runtime_enabled = (value != 0);
        break;
    case ZMK_SCROLL_INERTIA_RUNTIME_START:
        if (value < 0 || value > INT32_MAX / FP_SCALE) {
            return -ERANGE;
        }
        data->runtime_cfg.start_fp = value * FP_SCALE;
        break;
    case ZMK_SCROLL_INERTIA_RUNTIME_MOVE:
        if (value < 0) {
            return -ERANGE;
        }
        data->runtime_cfg.move = value;
        break;
    case ZMK_SCROLL_INERTIA_RUNTIME_STOP:
        if (value < 0 || value > INT32_MAX / FP_SCALE) {
            return -ERANGE;
        }
        data->runtime_cfg.stop_fp = value * FP_SCALE;
        break;
    default:
        return -EINVAL;
    }

    /* Never continue a coast/tracking gesture with half-old tuning. */
    to_idle(data);
    data->post_coast = false;
    return 0;
}

int zmk_scroll_inertia_runtime_get(const struct device *dev,
                                   enum zmk_scroll_inertia_runtime_param param,
                                   int32_t *value) {
    if (dev == NULL || value == NULL) {
        return -EINVAL;
    }

    struct scroll_inertia_data *data = dev->data;

    switch (param) {
    case ZMK_SCROLL_INERTIA_RUNTIME_ENABLED:
        *value = data->runtime_enabled ? 1 : 0;
        return 0;
    case ZMK_SCROLL_INERTIA_RUNTIME_START:
        *value = data->runtime_cfg.start_fp / FP_SCALE;
        return 0;
    case ZMK_SCROLL_INERTIA_RUNTIME_MOVE:
        *value = data->runtime_cfg.move;
        return 0;
    case ZMK_SCROLL_INERTIA_RUNTIME_STOP:
        *value = data->runtime_cfg.stop_fp / FP_SCALE;
        return 0;
    default:
        return -EINVAL;
    }
}

'''

    marker = "/* ------------------------------------------------------------------ */\n/* Device boilerplate                                                  */\n"
    if marker not in src:
        fail("device boilerplate marker not found")
    src = src.replace(marker, runtime_api + marker, 1)

    src = replace_once(
        src,
        "    data->dev = dev;\n    data->state = SS_IDLE;\n",
        "    data->dev = dev;\n"
        "    data->state = SS_IDLE;\n"
        "    data->runtime_cfg = *(const struct scroll_inertia_config *)dev->config;\n"
        "    data->runtime_enabled = true;\n",
        "runtime initialization",
    )

    src_path.write_text(src, encoding="utf-8")
    print(f"scroll-inertia runtime API patched at {EXPECTED_SHA[:12]}")


if __name__ == "__main__":
    main()
